apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
    
